In [1]:
# Order of complexity
import numpy as np

In [2]:
# random shuffle

l = np.array([2, 5, 8, 9, 0])
np.random.shuffle(l)

In [3]:
l

array([2, 8, 9, 0, 5])

In [4]:
# Binary search 
# finding n in l using binary search

In [5]:
l

array([2, 8, 9, 0, 5])

In [6]:
# Using recursion
def find_n(lst, left, right, n):
    if left > right:
        return -1
    else:
        mid = (left + right) // 2
        
        if lst[mid] == n:
            return mid
        elif lst[mid] < n:
            return find_n(lst, mid+1, right, n)
        else:
            return find_n(lst, left, mid-1, n)

In [7]:
n = 8
left, right = 0, len(l)-1
a = find_n(l, left, right, n)
print(a)

1


In [8]:
# Elements common in two lists
a = np.arange(-1, 10)
b = np.linspace(1, 9, 3, dtype=int)
print(a)
print(b)

[-1  0  1  2  3  4  5  6  7  8  9]
[1 5 9]


In [9]:
inter = set(a) & set(b)

In [10]:
print('Common elements',inter)

Common elements {1, 5, 9}
