<a href="https://colab.research.google.com/github/p-s-vishnu/Documents/blob/master/Python/Mine/Python_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics

- Numpy
- Pandas
- Matplotlib

- pillow 
- tessaract
- opencv

# Numpy

In [0]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
lst = [1, 11, 111, 1111]
dic = {'a':1, 'b':2, 'c':3}
st = {2, 4, 6}

In [12]:
print(np.array(lst))
print(type(np.array(lst)))

[   1   11  111 1111]
<class 'numpy.ndarray'>


In [13]:
print(np.array(dic))
print(type(np.array(dict)))

{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>


In [10]:
np.array(st)

array({2, 4, 6}, dtype=object)

In [21]:
# Comparing with usual method
L = range(1000)

%timeit [ i**2 for i in L]

1000 loops, best of 3: 295 µs per loop


In [19]:
a =  np.array([i for i in L])
%timeit a**2

The slowest run took 38.42 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.32 µs per loop


In [24]:
# Multidimensional arrays

a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [25]:
b = np.array([ [1,2,3], [4,5,6] ])
print(b.ndim)
print(b.shape)

2
(2, 3)


In [26]:
c = np.array([ [ [1,2] ], [ [3,4] ] ])
print(c.ndim)
print(c.shape)

3
(2, 1, 2)


In [32]:
# Arrange v/s Linspace, end is excluded
a = np.arange(0,10, 1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.linspace(1, 20, 3)    # 3rd parameter is the number of points, start end included
b

array([ 1. , 10.5, 20. ])

In [44]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [42]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [0]:
# diagonal


In [0]:
# rand v/s randn()

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
# slicing 

lst[0:3:2]

[1, 111]

In [58]:
# Copy and Views
# Shares memory

a = np.linspace(2, 6, 8)
b = a[0:5:2]
print(a, b)
print(np.shares_memory(a,b))

c = a[0:5:2].copy()
print(c)
print(np.shares_memory(a, c))

[2.         2.57142857 3.14285714 3.71428571 4.28571429 4.85714286
 5.42857143 6.        ] [2.         3.14285714 4.28571429]
True
[2.         3.14285714 4.28571429]
False


In [62]:
# Fancy indexing

a = np.arange(10, 100, 10)

# 1. mask
mask = a%2 == 0
print(a[mask])

# 2. multiple index
print(a[[0, 5, 7, 3]])

[10 20 30 40 50 60 70 80 90]
[10 60 80 40]
