<a href="https://colab.research.google.com/github/p-s-vishnu/Documents/blob/master/Python/Mine/Python_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics

- Numpy
- Pandas
- Matplotlib

- pillow 
- tessaract
- opencv

# Numpy

In [1]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
lst = [1, 11, 111, 1111]
dic = {'a':1, 'b':2, 'c':3}
st = {2, 4, 6}

In [12]:
print(np.array(lst))
print(type(np.array(lst)))

[   1   11  111 1111]
<class 'numpy.ndarray'>


In [13]:
print(np.array(dic))
print(type(np.array(dict)))

{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>


In [10]:
np.array(st)

array({2, 4, 6}, dtype=object)

In [21]:
# Comparing with usual method
L = range(1000)

%timeit [ i**2 for i in L]

1000 loops, best of 3: 295 µs per loop


In [19]:
a =  np.array([i for i in L])
%timeit a**2

The slowest run took 38.42 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.32 µs per loop


In [24]:
# Multidimensional arrays

a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [25]:
b = np.array([ [1,2,3], [4,5,6] ])
print(b.ndim)
print(b.shape)

2
(2, 3)


In [26]:
c = np.array([ [ [1,2] ], [ [3,4] ] ])
print(c.ndim)
print(c.shape)

3
(2, 1, 2)


In [32]:
# Arrange v/s Linspace, end is excluded
a = np.arange(0,10, 1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.linspace(1, 20, 3)    # 3rd parameter is the number of points, start end included
b

array([ 1. , 10.5, 20. ])

In [44]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [42]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [0]:
# diagonal


In [0]:
# rand v/s randn()

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
# slicing 

lst[0:3:2]

[1, 111]

In [58]:
# Copy and Views
# Shares memory

a = np.linspace(2, 6, 8)
b = a[0:5:2]
print(a, b)
print(np.shares_memory(a,b))

c = a[0:5:2].copy()
print(c)
print(np.shares_memory(a, c))

[2.         2.57142857 3.14285714 3.71428571 4.28571429 4.85714286
 5.42857143 6.        ] [2.         3.14285714 4.28571429]
True
[2.         3.14285714 4.28571429]
False


In [62]:
# Fancy indexing

a = np.arange(10, 100, 10)

# 1. mask
mask = a%2 == 0
print(a[mask])

# 2. multiple index
print(a[[0, 5, 7, 3]])

[10 20 30 40 50 60 70 80 90]
[10 60 80 40]


## operations

In [2]:
a = np.arange(10)

%timeit a**2

519 ns ± 1.93 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
b = np.linspace(1,20,10)
b

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [8]:
# element wise multiplication
c = a*b
c

array([  0.        ,   3.11111111,  10.44444444,  22.        ,
        37.77777778,  57.77777778,  82.        , 110.44444444,
       143.11111111, 180.        ])

In [10]:
print(a.shape)
print(b.shape)
print(c.shape)

(10,)
(10,)
(10,)


In [17]:
from numpy.random import randn

In [18]:
# mean 0 variance 1 - standard normal distribution
d = randn(10)
d

array([ 0.41532648,  1.01884628,  0.26474531,  0.41208525, -0.45967926,
       -0.14856279, -0.55278641, -0.29015031, -1.31954156, -1.0307296 ])

In [19]:
c = np.diag([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
c

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [29]:
# matrix multiplication
c * d

array([[  0.41532648,   0.        ,   0.        ,   0.        ,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ],
       [  0.        ,   2.03769255,   0.        ,   0.        ,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ],
       [  0.        ,   0.        ,   0.79423592,   0.        ,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ],
       [  0.        ,   0.        ,   0.        ,   1.64834099,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         -2.29839631,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         -0.        ,  -0.89137675,  -0.        ,  -0.        ,
         -0.        ,  -0.        ],
       [  

In [30]:
# dot product
# shape (10,)
c.dot(d)

array([  0.41532648,   2.03769255,   0.79423592,   1.64834099,
        -2.29839631,  -0.89137675,  -3.86950487,  -2.32120249,
       -11.87587402, -10.30729596])

In [35]:
a = np.array([1, 0, 1], dtype=bool)
b = np.array([1, 1, 1], dtype=bool)

In [36]:
np.logical_or(a, b)

array([ True,  True,  True])

In [37]:
np.logical_xor(a, b)

array([False,  True, False])

In [38]:
np.sin(a)

array([0.8413, 0.    , 0.8413], dtype=float16)

In [39]:
np.log(b)

array([0., 0., 0.], dtype=float16)

In [48]:
# summation
a = np.arange(10, 20).reshape(1,-1)
b = np.arange(10).reshape(1,-1)

print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))
# print(a.sum(b, axis=0))

145
[145]
[10 11 12 13 14 15 16 17 18 19]


In [51]:
# min-max
print(a.max())
print(a.argmax())

print(a.min())
print(a.argmin())

19
9
10
0


In [59]:
# logical operators
a1 = np.diag(np.arange(5))

print(np.any(a1 > 2))
print( (a1 > 0).all())

True
False


In [ ]:
# mean, median, std

In [60]:
# np.loadtxt('a.txt')

In [66]:
# broadcasting
# without reshape it is just a vector
a = np.array([10, 20, 30]).reshape(-1, 1)
print(a.shape)

b = np.array([9, 8, 7]).reshape(1, -1)
print(b.shape)

c = a + b
print(c, c.shape)

(3, 1)
(1, 3)
[[19 18 17]
 [29 28 27]
 [39 38 37]] (3, 3)


In [67]:
b + a

array([[19, 18, 17],
       [29, 28, 27],
       [39, 38, 37]])

In [69]:
b[:, :, np.newaxis]

array([[[9],
        [8],
        [7]]])

In [68]:
# np.tile(np.arange(), dim)

In [70]:
# flattening

b.ravel()

array([9, 8, 7])

In [71]:
# 3D meaning
# number of matrices x rows x columns
a[:, :, np.newaxis]

array([[[10]],

       [[20]],

       [[30]]])

In [84]:
d = np.arange(10)
d.resize((2,))
# d.resize((10,))

In [85]:
# truncates if size less
# pads with 0 if resize is greater
d

array([0, 1])

In [86]:
# sorting

np.sort(b)

array([[7, 8, 9]])

In [87]:
np.argsort(b)

array([[2, 1, 0]])

# Matplotlib